export const environment = {
    production: true,
supabaseUrl:https://zrzdptljtpgfutrzaqfq.supabase.co,
supabaseKey:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyemRwdGxqdHBnZnV0cnphcWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQyNjAyMzksImV4cCI6MTk3OTgzNjIzOX0.5cddPWXKD2OV_A-ORc8LVTsEuZHt88Dbtxr1Y2XsUjQ

};